version: '3'
services:
  pos-client:
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./src:/app/src
    environment:
      DISPLAY: unix$DISPLAY
    stdin_open: true
    tty: true
    command: bash
