services:
  pos-client:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./src:/app/src
    environment:
      DISPLAY: unix$DISPLAY
    tty: true
